/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface ContractConfigState {
  base_denom: string;
  contract_subaccount_id: string;
  market_id: string;
  owner: Addr;
  quote_denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  swap_spot: {
    price: FPDecimal;
    quantity: FPDecimal;
    [k: string]: unknown;
  };
};
export interface FPDecimal {
  num: string;
  sign: number;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  market_id: string;
  [k: string]: unknown;
}