/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Registry.types";
import * as _1 from "./Registry.client";
import * as _2 from "./AtomicOrder.types";
import * as _3 from "./AtomicOrder.client";
export namespace contracts {
  export const Registry = { ..._0,
    ..._1
  };
  export const AtomicOrder = { ..._2,
    ..._3
  };
}