/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  register: {
    contract_address: Addr;
    gas_limit: number;
    gas_price: string;
    is_executable: boolean;
    [k: string]: unknown;
  };
} | {
  update: {
    contract_address: Addr;
    gas_limit: number;
    gas_price: string;
    [k: string]: unknown;
  };
} | {
  activate: {
    contract_address: Addr;
    [k: string]: unknown;
  };
} | {
  deactivate: {
    contract_address: Addr;
    [k: string]: unknown;
  };
};
export type Addr = string;
export interface GetActiveContractsResponse {
  contracts: ContractExecutionParams[];
  [k: string]: unknown;
}
export interface ContractExecutionParams {
  address: Addr;
  gas_limit: number;
  gas_price: string;
  is_executable: boolean;
  [k: string]: unknown;
}
export interface GetContractResponse {
  contract: ContractExecutionParams;
  [k: string]: unknown;
}
export interface GetContractsResponse {
  contracts: ContractExecutionParams[];
  [k: string]: unknown;
}
export interface InstantiateMsg {
  [k: string]: unknown;
}
export type QueryMsg = {
  get_contract: {
    contract_address: Addr;
    [k: string]: unknown;
  };
} | {
  get_contracts: {
    [k: string]: unknown;
  };
} | {
  get_active_contracts: {
    [k: string]: unknown;
  };
};